services:
  - type: web
    name: vinsmoke-bot-backend
    env: node
    plan: free
    buildCommand: npm ci --only=production
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: TRUST_PROXY
        value: "true"
    healthCheckPath: /api/health